// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteSessionReducer from "../complete_session_reducer";
import CreateSessionReducer from "../create_session_reducer";
import DeletePartOverrideReducer from "../delete_part_override_reducer";
import ForkPartReducer from "../fork_part_reducer";
import MergeSessionsReducer from "../merge_sessions_reducer";
import PlaceOrderReducer from "../place_order_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetNameReducer from "../set_name_reducer";
import UpdateFlowerSpecReducer from "../update_flower_spec_reducer";
import UpdatePartOverrideReducer from "../update_part_override_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type CompleteSessionParams = __Infer<typeof CompleteSessionReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type DeletePartOverrideParams = __Infer<typeof DeletePartOverrideReducer>;
export type ForkPartParams = __Infer<typeof ForkPartReducer>;
export type MergeSessionsParams = __Infer<typeof MergeSessionsReducer>;
export type PlaceOrderParams = __Infer<typeof PlaceOrderReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type UpdateFlowerSpecParams = __Infer<typeof UpdateFlowerSpecReducer>;
export type UpdatePartOverrideParams = __Infer<typeof UpdatePartOverrideReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

