import {
  BOTANICAL_CLASSES,
  EDGE_STYLES,
  FUSION_KINDS,
  INFLORESCENCE_KINDS,
  LEAF_ARRANGEMENTS,
  LEAF_SHAPES,
  PATTERN_KINDS,
  PETAL_ARRANGEMENTS,
  PETAL_SHAPES,
  PISTIL_STYLES,
  SEPAL_SHAPES,
  SERRATIONS,
  STEM_STYLES,
  STIGMA_SHAPES,
  SURFACE_TEXTURES,
  VEIN_PATTERNS,
  isVariant,
  type BotanicalClass,
  type EdgeStyle,
  type FlowerFamily,
  type FusionKind,
  type InflorescenceKind,
  type LeafArrangement,
  type LeafShape,
  type PatternKind,
  type PetalArrangement,
  type PetalShape,
  type PistilStyle,
  type SepalShape,
  type Serration,
  type StemStyle,
  type StigmaShape,
  type SurfaceTexture,
  type Symmetry,
  type VeinPattern,
} from "../../client/src/data/flower-enums.ts";

// ═══════════════════════════════════════════════════════════════════════════
// Colors
// ═══════════════════════════════════════════════════════════════════════════

export const PALETTE_NAMES = [
  "crimson",
  "scarlet",
  "coral",
  "pink",
  "magenta",
  "blush",
  "peach",
  "apricot",
  "orange",
  "gold",
  "yellow",
  "cream",
  "ivory",
  "white",
  "lavender",
  "lilac",
  "violet",
  "plum",
  "indigo",
  "blue",
  "sky",
  "teal",
  "green",
  "lime",
  "burgundy",
  "brown",
  "black",
  "silver",
] as const;
export type PaletteName = (typeof PALETTE_NAMES)[number];

export const PALETTE: Record<PaletteName, string> = {
  crimson: "#dc2626",
  scarlet: "#ef4444",
  coral: "#fb7185",
  pink: "#ec4899",
  magenta: "#c026d3",
  blush: "#fbcfe8",
  peach: "#fdba74",
  apricot: "#fcd34d",
  orange: "#f97316",
  gold: "#eab308",
  yellow: "#facc15",
  cream: "#fef3c7",
  ivory: "#fffbeb",
  white: "#f5f5f5",
  lavender: "#c4b5fd",
  lilac: "#d8b4fe",
  violet: "#a855f7",
  plum: "#6b21a8",
  indigo: "#6366f1",
  blue: "#3b82f6",
  sky: "#7dd3fc",
  teal: "#14b8a6",
  green: "#22c55e",
  lime: "#a3e635",
  burgundy: "#7f1d1d",
  brown: "#92400e",
  black: "#171717",
  silver: "#d4d4d8",
};

export const LEAF_COLOR_NAMES = [
  "light",
  "dark",
  "blue_green",
  "bronze",
  "purple",
  "silver",
] as const;
export type LeafColorName = (typeof LEAF_COLOR_NAMES)[number];

export const LEAF_COLORS: Record<LeafColorName, string> = {
  light: "#4ade80",
  dark: "#166534",
  blue_green: "#5eead4",
  bronze: "#a16207",
  purple: "#6b21a8",
  silver: "#a1a1aa",
};

export const STEM_COLOR_NAMES = [
  "green",
  "red",
  "purple",
  "black",
  "silver",
  "brown",
] as const;
export type StemColorName = (typeof STEM_COLOR_NAMES)[number];

export const STEM_COLORS: Record<StemColorName, string> = {
  green: "#15803d",
  red: "#991b1b",
  purple: "#581c87",
  black: "#171717",
  silver: "#a1a1aa",
  brown: "#78350f",
};

export const SEPAL_COLOR_NAMES = [
  "green",
  "matching",
  "contrasting",
  "dark",
] as const;
export type SepalColorName = (typeof SEPAL_COLOR_NAMES)[number];

export type Rgba = { r: number; g: number; b: number; a: number };

export const round3 = (value: number): number =>
  Math.round(value * 1000) / 1000;

export function hexToRgba(hex: string): Rgba {
  const value = parseInt(hex.slice(1), 16);
  return {
    r: round3(((value >> 16) & 0xff) / 255),
    g: round3(((value >> 8) & 0xff) / 255),
    b: round3((value & 0xff) / 255),
    a: 1,
  };
}

export function darken(color: Rgba, factor: number): Rgba {
  return {
    r: round3(color.r * factor),
    g: round3(color.g * factor),
    b: round3(color.b * factor),
    a: color.a,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// Profile type
// ═══════════════════════════════════════════════════════════════════════════

export const STAMEN_PROMINENCES = [
  "hidden",
  "visible",
  "prominent",
  "brush",
] as const;
export type StamenProminence = (typeof STAMEN_PROMINENCES)[number];

export const SPECIAL_STRUCTURES = [
  "None",
  "Labellum",
  "Corona",
  "Spur",
  "Umbel",
  "Composite",
  "Bell",
] as const;
export type SpecialStructure = (typeof SPECIAL_STRUCTURES)[number];

export const STRANGENESS = ["faithful", "stylized", "invented"] as const;
export type Strangeness = (typeof STRANGENESS)[number];
export const STRANGENESS_DESCRIPTIONS: Readonly<Record<Strangeness, string>> = {
  faithful:
    "a real flower as it grows: every part inside what the family allows",
  stylized:
    "a real flower with artistic surface choices: unusual colors, textures, patterns, glow",
  invented:
    "a species that does not exist: the skeleton of the family with any structure, ornament or effect",
};

export type FamilyProfile = {
  key: FlowerFamily;
  description: string;
  examples: readonly string[];
  typicalGenus: string;
  botanicalClass: BotanicalClass;
  petalCounts: readonly number[];
  layerRange: readonly [number, number];
  symmetry: Symmetry;
  symmetryOrder: number;
  arrangements: readonly PetalArrangement[];
  shapes: readonly PetalShape[];
  innerShapes: readonly PetalShape[];
  edges: readonly EdgeStyle[];
  textures: readonly SurfaceTexture[];
  veins: readonly VeinPattern[];
  patterns: readonly PatternKind[];
  fusions: readonly FusionKind[];
  inflorescences: readonly InflorescenceKind[];
  disc: boolean;
  receptacleSize: readonly [number, number];
  stamenRange: readonly [number, number];
  stamenProminence: readonly StamenProminence[];
  pistilStyles: readonly PistilStyle[];
  stigmaShapes: readonly StigmaShape[];
  sepalCount: number;
  sepalShapes: readonly SepalShape[];
  leafShapes: readonly LeafShape[];
  serrations: readonly Serration[];
  leafArrangements: readonly LeafArrangement[];
  stemStyles: readonly StemStyle[];
  thorns: boolean;
  bracts: boolean;
  special: SpecialStructure;
  colors: readonly PaletteName[];
  leafColor: LeafColorName;
};

type StringListName = {
  [K in keyof FamilyProfile]: FamilyProfile[K] extends readonly string[]
    ? K
    : never;
}[keyof FamilyProfile];
export type ListName = Exclude<StringListName, "examples">;
export type FamilyLists = Pick<FamilyProfile, ListName>;

export const FULL_LISTS: FamilyLists = {
  arrangements: PETAL_ARRANGEMENTS,
  shapes: PETAL_SHAPES,
  innerShapes: PETAL_SHAPES,
  edges: EDGE_STYLES,
  textures: SURFACE_TEXTURES,
  veins: VEIN_PATTERNS,
  patterns: PATTERN_KINDS,
  fusions: FUSION_KINDS,
  inflorescences: INFLORESCENCE_KINDS,
  stamenProminence: STAMEN_PROMINENCES,
  pistilStyles: PISTIL_STYLES,
  stigmaShapes: STIGMA_SHAPES,
  sepalShapes: SEPAL_SHAPES,
  leafShapes: LEAF_SHAPES,
  serrations: SERRATIONS,
  leafArrangements: LEAF_ARRANGEMENTS,
  stemStyles: STEM_STYLES,
  colors: PALETTE_NAMES,
};

export const SURFACE_LISTS = [
  "textures",
  "edges",
  "veins",
  "patterns",
  "colors",
] as const satisfies readonly ListName[];

const opensUnder: Record<Strangeness, (listName: ListName) => boolean> = {
  faithful: () => false,
  stylized: listName => isVariant(SURFACE_LISTS, listName),
  invented: () => true,
};

export function legalList<K extends ListName>(
  profile: FamilyProfile,
  strangeness: Strangeness,
  listName: K,
): FamilyLists[K] {
  return opensUnder[strangeness](listName)
    ? FULL_LISTS[listName]
    : profile[listName];
}

// ═══════════════════════════════════════════════════════════════════════════
// Profiles. Index 0 of every list is the family default.
// ═══════════════════════════════════════════════════════════════════════════

export const FAMILIES: Record<FlowerFamily, FamilyProfile> = {
  Invented: {
    key: "Invented",
    description:
      "no real family: a dream plant, alien flora or anything that fits no botanical family; only internal consistency rules apply",
    examples: ["an invented species", "a flower from a dream", "alien flora"],
    typicalGenus: "Novaflora",
    botanicalClass: BOTANICAL_CLASSES[0],
    petalCounts: [3, 4, 5, 6, 8, 13, 21, 34],
    layerRange: [1, 4],
    symmetry: "Radial",
    symmetryOrder: 0,
    arrangements: PETAL_ARRANGEMENTS,
    shapes: PETAL_SHAPES,
    innerShapes: PETAL_SHAPES,
    edges: EDGE_STYLES,
    textures: SURFACE_TEXTURES,
    veins: VEIN_PATTERNS,
    patterns: PATTERN_KINDS,
    fusions: FUSION_KINDS,
    inflorescences: INFLORESCENCE_KINDS,
    disc: false,
    receptacleSize: [0.1, 0.8],
    stamenRange: [0, 100],
    stamenProminence: STAMEN_PROMINENCES,
    pistilStyles: PISTIL_STYLES,
    stigmaShapes: STIGMA_SHAPES,
    sepalCount: 5,
    sepalShapes: SEPAL_SHAPES,
    leafShapes: LEAF_SHAPES,
    serrations: SERRATIONS,
    leafArrangements: LEAF_ARRANGEMENTS,
    stemStyles: STEM_STYLES,
    thorns: false,
    bracts: false,
    special: "None",
    colors: PALETTE_NAMES,
    leafColor: "dark",
  },
  Rosaceae: {
    key: "Rosaceae",
    description:
      "rose family: five broad petals, or many petals spiralled into a double bloom, many stamens, thorny woody stems, pinnate serrated leaves",
    examples: ["rose", "spray rose", "cherry blossom", "apple blossom"],
    typicalGenus: "Rosa",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 4],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Spiral", "Radial", "Imbricate"],
    shapes: ["Obovate", "Orbicular", "Cordate", "Ovate"],
    innerShapes: ["Obovate", "Cuneate", "Ovate"],
    edges: ["Smooth", "Undulate", "Ruffled", "Rolled"],
    textures: ["Velvet", "Silk", "Smooth"],
    veins: ["Branching", "None", "Reticulate"],
    patterns: ["None", "Picotee", "Flame", "Band"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Spray", "Corymb"],
    disc: false,
    receptacleSize: [0.3, 0.5],
    stamenRange: [20, 60],
    stamenProminence: ["prominent", "visible", "hidden"],
    pistilStyles: ["Compound", "Simple"],
    stigmaShapes: ["Capitate", "Lobed"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Leaflike", "Ovate"],
    leafShapes: ["Pinnate", "Ovate", "Elliptic"],
    serrations: ["Fine", "Dentate", "Coarse"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Straight", "Woody", "Arching"],
    thorns: true,
    bracts: false,
    special: "None",
    colors: [
      "crimson",
      "pink",
      "blush",
      "white",
      "cream",
      "peach",
      "gold",
      "coral",
      "burgundy",
    ],
    leafColor: "dark",
  },
  Asteraceae: {
    key: "Asteraceae",
    description:
      "daisy family: a composite head with a central disc of tiny florets ringed by strap shaped ray petals, involucre of green bracts under the head",
    examples: [
      "sunflower",
      "daisy",
      "gerbera",
      "aster",
      "chrysanthemum",
      "dahlia",
      "zinnia",
    ],
    typicalGenus: "Aster",
    botanicalClass: "Dicot",
    petalCounts: [8, 13, 21, 34],
    layerRange: [1, 3],
    symmetry: "Radial",
    symmetryOrder: 0,
    arrangements: ["Radial", "Whorled", "Imbricate"],
    shapes: ["Ligulate"],
    innerShapes: ["Ligulate", "Tubular", "Filiform", "Lanceolate"],
    edges: ["Smooth", "Dentate", "Fringed", "Rolled"],
    textures: ["Smooth", "Silk", "Papery", "Velvet"],
    veins: ["Parallel", "None", "Branching"],
    patterns: ["None", "Band", "Stripes", "ThroatBlotch"],
    fusions: ["Free", "Tube"],
    inflorescences: ["Solitary", "Spray", "Corymb", "Panicle"],
    disc: true,
    receptacleSize: [0.5, 0.9],
    stamenRange: [0, 8],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Simple", "Split"],
    stigmaShapes: ["Bifid", "Discoid", "Capitate"],
    sepalCount: 0,
    sepalShapes: ["Leaflike", "Lanceolate"],
    leafShapes: ["Lanceolate", "Ovate", "Cordate", "Pinnate", "Linear"],
    serrations: ["Coarse", "Fine", "None", "Lobed"],
    leafArrangements: ["Alternate", "Opposite", "Basal"],
    stemStyles: ["Straight", "Arching"],
    thorns: false,
    bracts: true,
    special: "Composite",
    colors: [
      "yellow",
      "gold",
      "white",
      "orange",
      "pink",
      "violet",
      "crimson",
      "burgundy",
      "lavender",
    ],
    leafColor: "dark",
  },
  Fabaceae: {
    key: "Fabaceae",
    description:
      "pea family: butterfly shaped bilateral flower with a broad upright banner, two side wings and a keel, twining or climbing stems, pinnate leaves",
    examples: ["sweet pea", "lupin", "wisteria", "clover", "broom"],
    typicalGenus: "Lathyrus",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Bilateral",
    symmetryOrder: 0,
    arrangements: ["Papilionaceous", "Bilateral", "Zygomorphic"],
    shapes: ["Orbicular", "Obovate", "Reniform", "Flabellate"],
    innerShapes: ["Falcate", "Oblong", "Obovate"],
    edges: ["Undulate", "Smooth", "Ruffled", "Crisped"],
    textures: ["Silk", "Smooth", "Papery", "Velvet"],
    veins: ["Branching", "Reticulate", "None"],
    patterns: ["None", "Flame", "Picotee", "Stripes", "ThroatBlotch"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Raceme", "Spike"],
    disc: false,
    receptacleSize: [0.2, 0.4],
    stamenRange: [10, 10],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Simple"],
    stigmaShapes: ["Capitate", "Clavate"],
    sepalCount: 5,
    sepalShapes: ["Tubular", "Triangular", "Lanceolate"],
    leafShapes: ["Pinnate", "Ovate", "Bipinnate", "Elliptic"],
    serrations: ["None"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Twining", "Straight", "Trailing", "Arching", "Woody"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "pink",
      "lavender",
      "violet",
      "white",
      "crimson",
      "coral",
      "blush",
      "yellow",
    ],
    leafColor: "light",
  },
  Lamiaceae: {
    key: "Lamiaceae",
    description:
      "mint family: small two lipped tubular flowers stacked in spikes or whorls up a square stem, opposite aromatic leaves",
    examples: ["salvia", "lavender", "bells of Ireland", "mint", "sage"],
    typicalGenus: "Salvia",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Bilateral",
    symmetryOrder: 0,
    arrangements: ["Zygomorphic", "Bilateral"],
    shapes: ["Oblong", "Obovate", "Ovate", "Spatulate"],
    innerShapes: ["Oblong", "Lanceolate"],
    edges: ["Lobed", "Smooth", "Undulate", "Crisped"],
    textures: ["Velvet", "Hairy", "Smooth", "Fuzzy"],
    veins: ["None", "Branching"],
    patterns: ["None", "ThroatBlotch", "Spots", "Stripes"],
    fusions: ["Tube", "Free", "Bell"],
    inflorescences: ["Spike", "Solitary", "Raceme", "Panicle"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [2, 4],
    stamenProminence: ["visible", "hidden", "prominent"],
    pistilStyles: ["Gynobasic", "Split", "Simple"],
    stigmaShapes: ["Bifid", "Capitate"],
    sepalCount: 5,
    sepalShapes: ["Tubular", "Triangular", "Aristate"],
    leafShapes: ["Ovate", "Lanceolate", "Cordate", "Elliptic"],
    serrations: ["Crenate", "Dentate", "Fine", "None"],
    leafArrangements: ["Opposite", "Decussate", "Whorled"],
    stemStyles: ["Straight", "Arching", "Woody"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "violet",
      "lavender",
      "indigo",
      "blue",
      "crimson",
      "pink",
      "white",
      "magenta",
    ],
    leafColor: "dark",
  },
  Ranunculaceae: {
    key: "Ranunculaceae",
    description:
      "buttercup family: glossy or papery petals in variable numbers around a boss of many stamens, deeply cut palmate leaves; includes tall spikes of delphinium",
    examples: [
      "ranunculus",
      "buttercup",
      "anemone",
      "delphinium",
      "larkspur",
      "clematis",
      "hellebore",
    ],
    typicalGenus: "Ranunculus",
    botanicalClass: "Dicot",
    petalCounts: [5, 6, 8, 13],
    layerRange: [1, 5],
    symmetry: "Radial",
    symmetryOrder: 0,
    arrangements: ["Radial", "Spiral", "Imbricate", "Whorled"],
    shapes: ["Orbicular", "Obovate", "Ovate", "Cordate", "Cuneate"],
    innerShapes: ["Obovate", "Orbicular", "Cuneate", "Spatulate"],
    edges: ["Smooth", "Undulate", "Ruffled", "Erose"],
    textures: ["Silk", "Papery", "Smooth", "Waxy", "Glassy"],
    veins: ["Branching", "None", "Reticulate", "Palmate"],
    patterns: ["None", "Picotee", "Band", "Flame"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Spike", "Raceme", "Panicle"],
    disc: false,
    receptacleSize: [0.3, 0.6],
    stamenRange: [20, 80],
    stamenProminence: ["prominent", "visible", "hidden"],
    pistilStyles: ["Compound", "Branched", "Simple"],
    stigmaShapes: ["Capitate", "Clavate", "Lobed"],
    sepalCount: 5,
    sepalShapes: ["Petaloid", "Ovate", "Lanceolate", "Leaflike"],
    leafShapes: ["Palmate", "Lyrate", "Pinnate", "Reniform", "Cordate"],
    serrations: ["Lobed", "Coarse", "Dentate", "Doubly"],
    leafArrangements: ["Alternate", "Basal"],
    stemStyles: ["Straight", "Arching", "Sinuous"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "yellow",
      "white",
      "crimson",
      "pink",
      "orange",
      "violet",
      "indigo",
      "blue",
      "peach",
      "cream",
    ],
    leafColor: "dark",
  },
  Solanaceae: {
    key: "Solanaceae",
    description:
      "nightshade family: five petals fused into a funnel or bell, often pleated or velvety, with a dark or pale throat",
    examples: ["petunia", "nicotiana", "datura", "potato flower", "brugmansia"],
    typicalGenus: "Petunia",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Contorted", "Valvate"],
    shapes: ["Deltoid", "Ovate", "Obovate", "Orbicular"],
    innerShapes: ["Ovate", "Deltoid"],
    edges: ["Smooth", "Undulate", "Ruffled", "Plicate", "Lobed"],
    textures: ["Velvet", "Silk", "Smooth", "Hairy"],
    veins: ["Branching", "Reticulate", "Anastomosing", "None"],
    patterns: ["None", "ThroatBlotch", "Stripes", "Picotee", "Speckle"],
    fusions: ["Funnel", "Bell", "Free", "Trumpet", "Tube"],
    inflorescences: ["Solitary", "Raceme", "Spray"],
    disc: false,
    receptacleSize: [0.2, 0.4],
    stamenRange: [5, 5],
    stamenProminence: ["hidden", "visible", "prominent"],
    pistilStyles: ["Simple", "Capitate"],
    stigmaShapes: ["Capitate", "Bifid", "Discoid"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Triangular", "Tubular", "Leaflike"],
    leafShapes: ["Ovate", "Elliptic", "Lanceolate", "Cordate"],
    serrations: ["None", "Lobed", "Coarse"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Straight", "Trailing", "Sinuous", "Woody"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "violet",
      "magenta",
      "pink",
      "white",
      "crimson",
      "indigo",
      "yellow",
      "burgundy",
      "lavender",
    ],
    leafColor: "dark",
  },
  Brassicaceae: {
    key: "Brassicaceae",
    description:
      "mustard family: four clawed petals in a cross, six stamens, flowers packed in a raceme, basal rosette of leaves",
    examples: ["stock", "wallflower", "candytuft", "rocket", "honesty"],
    typicalGenus: "Matthiola",
    botanicalClass: "Dicot",
    petalCounts: [4],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 4,
    arrangements: ["Cruciform", "Radial"],
    shapes: ["Unguiculate", "Spatulate", "Obovate", "Orbicular"],
    innerShapes: ["Obovate", "Spatulate"],
    edges: ["Smooth", "Undulate", "Ruffled"],
    textures: ["Silk", "Smooth", "Papery", "Velvet"],
    veins: ["Branching", "None"],
    patterns: ["None", "Flame", "Picotee"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Raceme", "Spike", "Corymb"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [6, 6],
    stamenProminence: ["visible", "hidden"],
    pistilStyles: ["Simple"],
    stigmaShapes: ["Capitate", "Bifid"],
    sepalCount: 4,
    sepalShapes: ["Lanceolate", "Ovate"],
    leafShapes: ["Oblanceolate", "Lanceolate", "Lyrate", "Ovate"],
    serrations: ["None", "Lobed", "Dentate"],
    leafArrangements: ["Alternate", "Basal", "Rosette"],
    stemStyles: ["Straight", "Arching"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "white",
      "lavender",
      "pink",
      "violet",
      "cream",
      "yellow",
      "crimson",
      "peach",
    ],
    leafColor: "blue_green",
  },
  Malvaceae: {
    key: "Malvaceae",
    description:
      "mallow family: five overlapping silky petals opening wide around a central column of fused stamens, palmate leaves, often woody",
    examples: ["hibiscus", "hollyhock", "mallow", "lavatera", "abutilon"],
    typicalGenus: "Hibiscus",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Contorted", "Imbricate"],
    shapes: ["Obovate", "Orbicular", "Flabellate", "Cuneate"],
    innerShapes: ["Obovate", "Orbicular"],
    edges: ["Undulate", "Smooth", "Ruffled", "Crisped", "Erose"],
    textures: ["Silk", "Papery", "Velvet", "Smooth"],
    veins: ["Branching", "Reticulate", "Palmate"],
    patterns: ["None", "ThroatBlotch", "Flame", "Stripes", "Picotee"],
    fusions: ["Free", "Trumpet", "Funnel"],
    inflorescences: ["Solitary", "Raceme", "Spike"],
    disc: false,
    receptacleSize: [0.3, 0.5],
    stamenRange: [30, 100],
    stamenProminence: ["prominent", "brush", "visible"],
    pistilStyles: ["Branched", "Compound", "Split"],
    stigmaShapes: ["Capitate", "Lobed", "Stellate"],
    sepalCount: 5,
    sepalShapes: ["Triangular", "Lanceolate", "Leaflike"],
    leafShapes: ["Palmate", "Cordate", "Ovate", "Lyrate"],
    serrations: ["Dentate", "Lobed", "Crenate", "Coarse"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Woody", "Straight", "Arching"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "crimson",
      "scarlet",
      "pink",
      "coral",
      "orange",
      "yellow",
      "white",
      "magenta",
      "peach",
      "blush",
    ],
    leafColor: "dark",
  },
  Caryophyllaceae: {
    key: "Caryophyllaceae",
    description:
      "carnation family: five fringed or toothed clawed petals, often doubled into a ruffled pom, tubular calyx, narrow grey green opposite leaves on jointed stems",
    examples: [
      "carnation",
      "mini carnation",
      "sweet William",
      "pink",
      "gypsophila",
    ],
    typicalGenus: "Dianthus",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 4],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Imbricate", "Spiral", "Contorted"],
    shapes: ["Unguiculate", "Flabellate", "Obovate", "Cuneate"],
    innerShapes: ["Flabellate", "Cuneate", "Obovate"],
    edges: ["Fringed", "Dentate", "Ruffled", "Serrated", "Crisped", "Lacerate"],
    textures: ["Silk", "Smooth", "Velvet", "Papery"],
    veins: ["Branching", "None", "Dichotomous"],
    patterns: ["None", "Picotee", "Speckle", "Band", "Stripes", "ThroatBlotch"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Panicle", "Spray", "Corymb"],
    disc: false,
    receptacleSize: [0.2, 0.4],
    stamenRange: [10, 10],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Split", "Branched", "Simple"],
    stigmaShapes: ["Bifid", "Trifid", "Plumose"],
    sepalCount: 5,
    sepalShapes: ["Tubular", "Triangular", "Aristate"],
    leafShapes: ["Linear", "Lanceolate", "Oblanceolate"],
    serrations: ["None"],
    leafArrangements: ["Opposite", "Decussate"],
    stemStyles: ["Straight", "Zigzag", "Arching"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "pink",
      "crimson",
      "white",
      "coral",
      "magenta",
      "peach",
      "burgundy",
      "lavender",
      "cream",
      "yellow",
    ],
    leafColor: "blue_green",
  },
  Ericaceae: {
    key: "Ericaceae",
    description:
      "heath family: small bell or urn shaped fused flowers in racemes, needle like or leathery evergreen leaves on woody stems",
    examples: ["heather", "erica", "rhododendron", "azalea", "blueberry"],
    typicalGenus: "Erica",
    botanicalClass: "Dicot",
    petalCounts: [4, 5],
    layerRange: [1, 1],
    symmetry: "Radial",
    symmetryOrder: 0,
    arrangements: ["Radial", "Valvate", "Whorled"],
    shapes: ["Ovate", "Deltoid", "Orbicular", "Oblong"],
    innerShapes: ["Ovate", "Deltoid"],
    edges: ["Smooth", "Lobed", "Undulate", "Revolute"],
    textures: ["Waxy", "Smooth", "Papery", "Hairy", "Powdery"],
    veins: ["None", "Branching"],
    patterns: ["None", "Spots", "Speckle", "ThroatBlotch", "Flame"],
    fusions: ["Bell", "Urn", "Tube", "Funnel"],
    inflorescences: ["Solitary", "Raceme", "Spike", "Umbel", "Corymb"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [8, 10],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Simple", "Capitate"],
    stigmaShapes: ["Capitate", "Discoid", "Lobed"],
    sepalCount: 4,
    sepalShapes: ["Triangular", "Ovate", "Lanceolate", "Petaloid"],
    leafShapes: ["Acicular", "Linear", "Elliptic", "Ovate", "Obovate"],
    serrations: ["None", "Fine", "Ciliate"],
    leafArrangements: ["Whorled", "Alternate", "Opposite"],
    stemStyles: ["Woody", "Straight", "Arching"],
    thorns: false,
    bracts: false,
    special: "Bell",
    colors: [
      "pink",
      "magenta",
      "white",
      "lavender",
      "crimson",
      "blush",
      "violet",
    ],
    leafColor: "dark",
  },
  Papaveraceae: {
    key: "Papaveraceae",
    description:
      "poppy family: four or six crumpled papery petals around a dark boss of many stamens and a pepperpot capsule, two sepals that fall as the bud opens",
    examples: ["poppy", "Iceland poppy", "opium poppy", "California poppy"],
    typicalGenus: "Papaver",
    botanicalClass: "Dicot",
    petalCounts: [4, 6],
    layerRange: [1, 3],
    symmetry: "Radial",
    symmetryOrder: 2,
    arrangements: ["Radial", "Imbricate", "Contorted", "Whorled"],
    shapes: ["Orbicular", "Obovate", "Flabellate", "Reniform"],
    innerShapes: ["Obovate", "Orbicular", "Cuneate"],
    edges: ["Smooth", "Crisped", "Undulate", "Ruffled", "Erose", "Fringed"],
    textures: ["Papery", "Silk", "Smooth", "Glassy"],
    veins: ["Branching", "None", "Dichotomous", "Reticulate"],
    patterns: ["None", "ThroatBlotch", "Spots", "Picotee", "Band"],
    fusions: ["Free"],
    inflorescences: ["Solitary"],
    disc: false,
    receptacleSize: [0.4, 0.7],
    stamenRange: [30, 150],
    stamenProminence: ["prominent", "brush", "visible"],
    pistilStyles: ["Capitate", "Compound"],
    stigmaShapes: ["Discoid", "Lobed", "Stellate", "Capitate"],
    sepalCount: 2,
    sepalShapes: ["Ovate", "Leaflike"],
    leafShapes: ["Pinnate", "Lyrate", "Bipinnate", "Lanceolate"],
    serrations: ["Lobed", "Coarse", "Dentate", "Doubly"],
    leafArrangements: ["Basal", "Alternate", "Rosette"],
    stemStyles: ["Arching", "Straight", "Sinuous"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "scarlet",
      "crimson",
      "orange",
      "coral",
      "white",
      "pink",
      "yellow",
      "peach",
      "violet",
      "black",
    ],
    leafColor: "blue_green",
  },
  Violaceae: {
    key: "Violaceae",
    description:
      "violet family: five bilateral petals with a face like pattern of dark veins and a nectar spur behind, heart shaped leaves in a low rosette",
    examples: ["violet", "pansy", "viola", "heartsease"],
    typicalGenus: "Viola",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 1],
    symmetry: "Bilateral",
    symmetryOrder: 0,
    arrangements: ["Zygomorphic", "Bilateral"],
    shapes: ["Obovate", "Orbicular", "Spatulate", "Oblong"],
    innerShapes: ["Obovate", "Spatulate", "Cordate"],
    edges: ["Smooth", "Undulate", "Ruffled", "Erose"],
    textures: ["Velvet", "Silk", "Smooth"],
    veins: ["Branching", "Dichotomous", "None", "Palmate"],
    patterns: ["None", "ThroatBlotch", "Stripes", "Flame", "Picotee", "Band"],
    fusions: ["Free", "Tube"],
    inflorescences: ["Solitary"],
    disc: false,
    receptacleSize: [0.1, 0.2],
    stamenRange: [5, 5],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Simple", "Capitate"],
    stigmaShapes: ["Capitate", "Clavate", "Lobed"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Ovate", "Aristate"],
    leafShapes: ["Cordate", "Reniform", "Ovate", "Orbicular", "Palmate"],
    serrations: ["Crenate", "Dentate", "Fine", "Lobed"],
    leafArrangements: ["Basal", "Rosette", "Alternate"],
    stemStyles: ["Straight", "Arching", "Trailing"],
    thorns: false,
    bracts: false,
    special: "Spur",
    colors: [
      "violet",
      "yellow",
      "white",
      "indigo",
      "lavender",
      "burgundy",
      "blue",
      "black",
      "orange",
      "cream",
    ],
    leafColor: "dark",
  },
  Primulaceae: {
    key: "Primulaceae",
    description:
      "primrose family: five flat notched petals around a contrasting central eye, flowers on stalks above a rosette of crinkled leaves",
    examples: ["primrose", "primula", "cyclamen", "polyanthus", "cowslip"],
    typicalGenus: "Primula",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Contorted", "Imbricate"],
    shapes: ["Obovate", "Cordate", "Orbicular", "Flabellate", "Oblong"],
    innerShapes: ["Obovate", "Orbicular"],
    edges: ["Smooth", "Lobed", "Undulate", "Fringed", "Dentate", "Ruffled"],
    textures: ["Velvet", "Silk", "Smooth", "Powdery", "Frosted"],
    veins: ["None", "Branching"],
    patterns: ["ThroatBlotch", "None", "Picotee", "Band", "Stripes"],
    fusions: ["Free", "Funnel", "Tube", "Bell"],
    inflorescences: ["Solitary", "Umbel", "Spike", "Raceme"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [5, 5],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Simple", "Capitate"],
    stigmaShapes: ["Capitate", "Discoid"],
    sepalCount: 5,
    sepalShapes: ["Tubular", "Triangular", "Lanceolate"],
    leafShapes: ["Obovate", "Spatulate", "Oblanceolate", "Ovate", "Orbicular"],
    serrations: ["Crenate", "Dentate", "None", "Fine"],
    leafArrangements: ["Rosette", "Basal", "Whorled"],
    stemStyles: ["Straight", "Arching"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "yellow",
      "cream",
      "pink",
      "magenta",
      "violet",
      "white",
      "crimson",
      "lavender",
      "blue",
      "orange",
    ],
    leafColor: "light",
  },
  Geraniaceae: {
    key: "Geraniaceae",
    description:
      "geranium family: five petals with dark veins or flame marks radiating from the base, beaked seed head, rounded lobed leaves, often scented",
    examples: ["pelargonium", "geranium", "cranesbill", "herb Robert"],
    typicalGenus: "Pelargonium",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Bilateral", "Imbricate"],
    shapes: ["Obovate", "Orbicular", "Cuneate", "Spatulate", "Unguiculate"],
    innerShapes: ["Obovate", "Orbicular"],
    edges: ["Smooth", "Undulate", "Ruffled", "Lobed", "Fringed"],
    textures: ["Silk", "Velvet", "Smooth", "Papery"],
    veins: ["Dichotomous", "Branching", "Palmate", "None"],
    patterns: ["Stripes", "Flame", "None", "ThroatBlotch", "Spots", "Picotee"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Umbel", "Corymb"],
    disc: false,
    receptacleSize: [0.2, 0.4],
    stamenRange: [10, 10],
    stamenProminence: ["visible", "hidden", "prominent"],
    pistilStyles: ["Split", "Branched", "Compound"],
    stigmaShapes: ["Stellate", "Lobed", "Bifid"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Aristate", "Ovate"],
    leafShapes: [
      "Palmate",
      "Reniform",
      "Orbicular",
      "Peltate",
      "Cordate",
      "Lyrate",
    ],
    serrations: ["Lobed", "Crenate", "Dentate", "Doubly"],
    leafArrangements: ["Opposite", "Alternate", "Basal"],
    stemStyles: ["Straight", "Succulent", "Zigzag", "Trailing", "Woody"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "magenta",
      "pink",
      "scarlet",
      "violet",
      "white",
      "lavender",
      "coral",
      "blush",
      "crimson",
    ],
    leafColor: "dark",
  },
  Boraginaceae: {
    key: "Boraginaceae",
    description:
      "forget-me-not family: tiny five lobed radial flowers with a yellow or white eye, held in coiled sprays that unroll as they open, hairy leaves",
    examples: ["forget-me-not", "borage", "comfrey", "heliotrope", "bugloss"],
    typicalGenus: "Myosotis",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 1],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Contorted", "Valvate"],
    shapes: ["Orbicular", "Obovate", "Ovate", "Deltoid"],
    innerShapes: ["Orbicular", "Obovate"],
    edges: ["Smooth", "Undulate", "Lobed"],
    textures: ["Smooth", "Silk", "Hairy", "Velvet"],
    veins: ["None", "Branching"],
    patterns: ["ThroatBlotch", "None", "Band", "Spots"],
    fusions: ["Free", "Funnel", "Tube", "Bell"],
    inflorescences: ["Solitary", "Raceme", "Panicle", "Spray", "Spike"],
    disc: false,
    receptacleSize: [0.1, 0.2],
    stamenRange: [5, 5],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Gynobasic", "Simple", "Split"],
    stigmaShapes: ["Capitate", "Bifid"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Triangular", "Aristate"],
    leafShapes: ["Lanceolate", "Oblanceolate", "Ovate", "Spatulate", "Linear"],
    serrations: ["None", "Ciliate", "Fine"],
    leafArrangements: ["Alternate", "Basal", "Rosette"],
    stemStyles: ["Straight", "Arching", "Sinuous"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "blue",
      "sky",
      "white",
      "pink",
      "violet",
      "indigo",
      "lavender",
      "yellow",
    ],
    leafColor: "light",
  },
  Convolvulaceae: {
    key: "Convolvulaceae",
    description:
      "morning glory family: five petals fused into a wide pleated funnel or trumpet that twists shut, twining stems, heart or arrow shaped leaves",
    examples: ["morning glory", "bindweed", "moonflower", "convolvulus"],
    typicalGenus: "Ipomoea",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 1],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Contorted", "Radial", "Valvate"],
    shapes: ["Deltoid", "Obovate", "Orbicular", "Reniform"],
    innerShapes: ["Deltoid", "Obovate"],
    edges: ["Smooth", "Undulate", "Plicate", "Lobed"],
    textures: ["Silk", "Smooth", "Glassy", "Velvet", "Papery"],
    veins: ["Branching", "Parallel", "Anastomosing", "None"],
    patterns: ["None", "Stripes", "ThroatBlotch", "Band", "Picotee", "Flame"],
    fusions: ["Funnel", "Trumpet", "Bell", "Free"],
    inflorescences: ["Solitary", "Umbel", "Spray"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [5, 5],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Simple", "Capitate"],
    stigmaShapes: ["Capitate", "Lobed", "Bifid"],
    sepalCount: 5,
    sepalShapes: ["Ovate", "Lanceolate", "Leaflike", "Aristate"],
    leafShapes: [
      "Cordate",
      "Sagittate",
      "Hastate",
      "Palmate",
      "Ovate",
      "Reniform",
    ],
    serrations: ["None", "Lobed"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Twining", "Trailing", "Sinuous", "Straight"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "blue",
      "violet",
      "indigo",
      "magenta",
      "pink",
      "white",
      "sky",
      "crimson",
      "lavender",
    ],
    leafColor: "dark",
  },
  Apiaceae: {
    key: "Apiaceae",
    description:
      "carrot family: hundreds of tiny five petalled flowers in flat lacy umbels on stalks from one point, finely divided feathery leaves, hollow ribbed stems",
    examples: [
      "Queen Anne's lace",
      "bupleurum",
      "dill",
      "fennel",
      "ammi",
      "cow parsley",
    ],
    typicalGenus: "Daucus",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 1],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Valvate", "Bilateral"],
    shapes: ["Obovate", "Cordate", "Ovate", "Orbicular", "Spatulate"],
    innerShapes: ["Obovate", "Ovate"],
    edges: ["Smooth", "Lobed", "Undulate"],
    textures: ["Smooth", "Papery", "Silk"],
    veins: ["None", "Branching"],
    patterns: ["None", "Spots"],
    fusions: ["Free"],
    inflorescences: ["Umbel", "Solitary", "Corymb", "Panicle"],
    disc: false,
    receptacleSize: [0.2, 0.5],
    stamenRange: [5, 5],
    stamenProminence: ["visible", "hidden", "prominent"],
    pistilStyles: ["Split", "Simple", "Branched"],
    stigmaShapes: ["Capitate", "Bifid", "Discoid"],
    sepalCount: 5,
    sepalShapes: ["Triangular", "Aristate", "Lanceolate"],
    leafShapes: ["Bipinnate", "Pinnate", "Palmate", "Lanceolate", "Linear"],
    serrations: ["Doubly", "Lobed", "Fine", "Dentate", "None"],
    leafArrangements: ["Alternate", "Basal"],
    stemStyles: ["Straight", "Arching", "Zigzag"],
    thorns: false,
    bracts: true,
    special: "Umbel",
    colors: [
      "white",
      "cream",
      "lime",
      "green",
      "blush",
      "pink",
      "burgundy",
      "yellow",
    ],
    leafColor: "light",
  },
  Caprifoliaceae: {
    key: "Caprifoliaceae",
    description:
      "honeysuckle family: long tubular two lipped bilateral flowers with protruding stamens, paired opposite leaves on twining or woody stems, sweetly scented",
    examples: ["honeysuckle", "weigela", "abelia", "scabious", "valerian"],
    typicalGenus: "Lonicera",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 1],
    symmetry: "Bilateral",
    symmetryOrder: 0,
    arrangements: ["Zygomorphic", "Bilateral", "Radial"],
    shapes: ["Oblong", "Ligulate", "Lanceolate", "Spatulate"],
    innerShapes: ["Ligulate", "Oblong"],
    edges: ["Smooth", "Lobed", "Rolled", "Revolute"],
    textures: ["Silk", "Smooth", "Waxy", "Hairy"],
    veins: ["None", "Branching"],
    patterns: ["None", "Flame", "Band", "ThroatBlotch"],
    fusions: ["Tube", "Free", "Funnel", "Trumpet", "Bell"],
    inflorescences: ["Solitary", "Spike", "Corymb", "Umbel", "Panicle"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [4, 5],
    stamenProminence: ["prominent", "visible", "hidden"],
    pistilStyles: ["Simple", "Capitate"],
    stigmaShapes: ["Capitate", "Discoid"],
    sepalCount: 5,
    sepalShapes: ["Triangular", "Tubular", "Lanceolate"],
    leafShapes: ["Ovate", "Elliptic", "Lanceolate", "Cordate", "Obovate"],
    serrations: ["None", "Fine", "Dentate", "Lobed"],
    leafArrangements: ["Opposite", "Decussate", "Whorled"],
    stemStyles: ["Twining", "Woody", "Arching", "Trailing", "Straight"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "cream",
      "yellow",
      "white",
      "peach",
      "coral",
      "pink",
      "crimson",
      "orange",
      "blush",
      "lavender",
    ],
    leafColor: "dark",
  },
  Hydrangeaceae: {
    key: "Hydrangeaceae",
    description:
      "hydrangea family: domed or flat corymbs of many small four or five petalled florets, showy sterile florets at the rim, broad toothed opposite leaves",
    examples: [
      "hydrangea",
      "mophead hydrangea",
      "lacecap hydrangea",
      "deutzia",
      "philadelphus",
    ],
    typicalGenus: "Hydrangea",
    botanicalClass: "Dicot",
    petalCounts: [4, 5],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 0,
    arrangements: ["Radial", "Valvate", "Imbricate", "Cruciform"],
    shapes: ["Obovate", "Ovate", "Orbicular", "Rhomboid", "Deltoid"],
    innerShapes: ["Obovate", "Ovate"],
    edges: ["Smooth", "Dentate", "Undulate", "Serrated"],
    textures: ["Papery", "Silk", "Smooth", "Velvet"],
    veins: ["Branching", "None", "Reticulate", "Palmate"],
    patterns: ["None", "Picotee", "Band", "Speckle"],
    fusions: ["Free"],
    inflorescences: ["Corymb", "Panicle", "Solitary", "Umbel"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [8, 10],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Split", "Simple", "Branched"],
    stigmaShapes: ["Capitate", "Bifid", "Trifid"],
    sepalCount: 4,
    sepalShapes: ["Petaloid", "Ovate", "Triangular"],
    leafShapes: ["Ovate", "Elliptic", "Cordate", "Palmate", "Obovate"],
    serrations: ["Coarse", "Dentate", "Fine", "Lobed"],
    leafArrangements: ["Opposite", "Decussate"],
    stemStyles: ["Woody", "Straight", "Arching"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "blue",
      "pink",
      "lavender",
      "white",
      "sky",
      "violet",
      "lime",
      "magenta",
      "cream",
      "burgundy",
    ],
    leafColor: "dark",
  },
  Magnoliaceae: {
    key: "Magnoliaceae",
    description:
      "magnolia family: large goblet flowers of six to twelve thick spoon shaped tepals in a spiral around a cone of many stamens, on bare woody branches",
    examples: ["magnolia", "tulip tree", "star magnolia", "champak"],
    typicalGenus: "Magnolia",
    botanicalClass: "Magnoliid",
    petalCounts: [6, 9, 12],
    layerRange: [2, 4],
    symmetry: "Spiral",
    symmetryOrder: 0,
    arrangements: ["Spiral", "Whorled", "Imbricate", "Valvate"],
    shapes: ["Spatulate", "Oblong", "Obovate", "Lanceolate", "Cuneate"],
    innerShapes: ["Spatulate", "Obovate", "Oblong"],
    edges: ["Smooth", "Undulate", "Rolled"],
    textures: ["Waxy", "Leathery", "Silk", "Smooth", "Velvet"],
    veins: ["None", "Parallel", "Branching"],
    patterns: ["None", "Flame", "Band", "ThroatBlotch"],
    fusions: ["Free"],
    inflorescences: ["Solitary"],
    disc: false,
    receptacleSize: [0.4, 0.7],
    stamenRange: [30, 150],
    stamenProminence: ["prominent", "visible", "brush"],
    pistilStyles: ["Compound", "Branched", "Simple"],
    stigmaShapes: ["Clavate", "Capitate", "Lobed"],
    sepalCount: 3,
    sepalShapes: ["Petaloid", "Leaflike", "Ovate", "Spatulate"],
    leafShapes: ["Obovate", "Elliptic", "Ovate", "Oblanceolate", "Lanceolate"],
    serrations: ["None"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Woody", "Straight", "Arching"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "white",
      "pink",
      "blush",
      "cream",
      "magenta",
      "violet",
      "yellow",
      "burgundy",
      "ivory",
    ],
    leafColor: "dark",
  },
  Paeoniaceae: {
    key: "Paeoniaceae",
    description:
      "peony family: huge bowl or bomb shaped flowers of five to ten broad ruffled petals, often doubled into a dense ball around a brush of golden stamens, deeply cut leaves",
    examples: ["peony", "tree peony", "coral charm peony", "itoh peony"],
    typicalGenus: "Paeonia",
    botanicalClass: "Dicot",
    petalCounts: [5, 8, 10],
    layerRange: [1, 5],
    symmetry: "Radial",
    symmetryOrder: 0,
    arrangements: ["Spiral", "Imbricate", "Radial", "Whorled"],
    shapes: ["Obovate", "Orbicular", "Flabellate", "Cuneate", "Oblong"],
    innerShapes: ["Cuneate", "Obovate", "Laciniate", "Filiform", "Flabellate"],
    edges: ["Ruffled", "Undulate", "Smooth", "Erose", "Crisped", "Lacerate"],
    textures: ["Silk", "Papery", "Velvet", "Smooth"],
    veins: ["None", "Branching"],
    patterns: ["None", "Flame", "Picotee", "Spots", "Band"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Spray"],
    disc: false,
    receptacleSize: [0.3, 0.5],
    stamenRange: [50, 200],
    stamenProminence: ["prominent", "brush", "hidden"],
    pistilStyles: ["Compound", "Branched", "Simple"],
    stigmaShapes: ["Lobed", "Capitate", "Fimbriate"],
    sepalCount: 5,
    sepalShapes: ["Leaflike", "Ovate", "Petaloid"],
    leafShapes: ["Pinnate", "Bipinnate", "Lanceolate", "Elliptic", "Lyrate"],
    serrations: ["Lobed", "None", "Coarse"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Straight", "Arching", "Woody"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "pink",
      "blush",
      "white",
      "coral",
      "crimson",
      "magenta",
      "cream",
      "peach",
      "burgundy",
      "yellow",
    ],
    leafColor: "dark",
  },
  Plumbaginaceae: {
    key: "Plumbaginaceae",
    description:
      "statice family: clouds of tiny papery flowers in branched winged panicles, the dry colored calyx outlasting the petals, basal rosette of lobed leaves",
    examples: ["statice", "limonium", "sea lavender", "thrift", "misty blue"],
    typicalGenus: "Limonium",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Valvate", "Whorled"],
    shapes: ["Obovate", "Spatulate", "Oblong", "Ovate"],
    innerShapes: ["Spatulate", "Oblong"],
    edges: ["Smooth", "Undulate", "Ruffled", "Crisped", "Plicate"],
    textures: ["Papery", "Smooth", "Frosted", "Silk", "Powdery"],
    veins: ["None", "Branching", "Parallel"],
    patterns: ["None", "Band", "Picotee"],
    fusions: ["Free", "Funnel", "Tube"],
    inflorescences: ["Panicle", "Solitary", "Spray", "Spike", "Corymb"],
    disc: false,
    receptacleSize: [0.1, 0.2],
    stamenRange: [5, 5],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Split", "Branched", "Simple"],
    stigmaShapes: ["Capitate", "Plumose", "Fimbriate"],
    sepalCount: 5,
    sepalShapes: ["Petaloid", "Tubular", "Aristate", "Triangular"],
    leafShapes: [
      "Oblanceolate",
      "Spatulate",
      "Lyrate",
      "Lanceolate",
      "Obovate",
    ],
    serrations: ["Lobed", "None", "Crenate"],
    leafArrangements: ["Rosette", "Basal", "Alternate"],
    stemStyles: ["Zigzag", "Straight", "Arching"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "lavender",
      "violet",
      "white",
      "pink",
      "blue",
      "yellow",
      "peach",
      "magenta",
      "indigo",
    ],
    leafColor: "blue_green",
  },
  Hypericaceae: {
    key: "Hypericaceae",
    description:
      "St John's wort family: five golden petals around a dense brush of long stamens, followed by glossy colored berries in sprays, small opposite leaves",
    examples: ["hypericum", "St John's wort", "rose of Sharon", "tutsan"],
    typicalGenus: "Hypericum",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 1],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Contorted", "Imbricate"],
    shapes: ["Obovate", "Oblong", "Ovate", "Falcate", "Spatulate"],
    innerShapes: ["Obovate", "Oblong"],
    edges: ["Smooth", "Undulate", "Erose", "Dentate"],
    textures: ["Smooth", "Silk", "Waxy", "Glassy"],
    veins: ["None", "Branching", "Dichotomous", "Arcuate"],
    patterns: ["None", "Spots", "Speckle", "Band"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Spray", "Corymb", "Panicle"],
    disc: false,
    receptacleSize: [0.3, 0.6],
    stamenRange: [30, 100],
    stamenProminence: ["brush", "prominent", "visible"],
    pistilStyles: ["Branched", "Split", "Compound"],
    stigmaShapes: ["Capitate", "Trifid", "Clavate"],
    sepalCount: 5,
    sepalShapes: ["Ovate", "Lanceolate", "Leaflike"],
    leafShapes: ["Elliptic", "Ovate", "Lanceolate", "Obovate", "Linear"],
    serrations: ["None"],
    leafArrangements: ["Opposite", "Decussate", "Whorled"],
    stemStyles: ["Woody", "Straight", "Arching", "Zigzag"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "yellow",
      "gold",
      "coral",
      "crimson",
      "peach",
      "orange",
      "cream",
      "burgundy",
      "green",
    ],
    leafColor: "dark",
  },
  Myrtaceae: {
    key: "Myrtaceae",
    description:
      "myrtle family: small waxy five petalled flowers with many stamens, needle like aromatic evergreen leaves on woody stems",
    examples: [
      "waxflower",
      "eucalyptus blossom",
      "myrtle",
      "bottlebrush",
      "tea tree",
    ],
    typicalGenus: "Chamelaucium",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 1],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Valvate", "Imbricate"],
    shapes: ["Orbicular", "Obovate", "Ovate", "Spatulate"],
    innerShapes: ["Orbicular", "Obovate"],
    edges: ["Smooth", "Undulate"],
    textures: ["Waxy", "Smooth", "Glassy", "Leathery", "Silk"],
    veins: ["None", "Branching"],
    patterns: ["None", "ThroatBlotch", "Band", "Picotee"],
    fusions: ["Free"],
    inflorescences: ["Solitary", "Spray", "Corymb", "Spike", "Umbel"],
    disc: false,
    receptacleSize: [0.3, 0.5],
    stamenRange: [10, 80],
    stamenProminence: ["prominent", "brush", "visible", "hidden"],
    pistilStyles: ["Simple", "Capitate", "Compound"],
    stigmaShapes: ["Capitate", "Discoid", "Clavate"],
    sepalCount: 5,
    sepalShapes: ["Triangular", "Ovate", "Lanceolate"],
    leafShapes: [
      "Acicular",
      "Linear",
      "Lanceolate",
      "Elliptic",
      "Falcate",
      "Ovate",
    ],
    serrations: ["None"],
    leafArrangements: ["Opposite", "Decussate", "Alternate", "Whorled"],
    stemStyles: ["Woody", "Straight", "Arching", "Zigzag"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "white",
      "pink",
      "blush",
      "magenta",
      "crimson",
      "scarlet",
      "cream",
      "lavender",
      "burgundy",
      "yellow",
    ],
    leafColor: "dark",
  },
  Plantaginaceae: {
    key: "Plantaginaceae",
    description:
      "snapdragon family: two lipped bilateral flowers with a closed mouth that pops open when squeezed, stacked up a dense spike, lance shaped leaves",
    examples: ["snapdragon", "foxglove", "penstemon", "veronica", "nemesia"],
    typicalGenus: "Antirrhinum",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Bilateral",
    symmetryOrder: 0,
    arrangements: ["Zygomorphic", "Bilateral"],
    shapes: ["Obovate", "Oblong", "Orbicular", "Reniform", "Flabellate"],
    innerShapes: ["Oblong", "Obovate", "Cordate"],
    edges: ["Lobed", "Undulate", "Smooth", "Ruffled", "Crisped", "Plicate"],
    textures: ["Velvet", "Silk", "Smooth", "Hairy"],
    veins: ["Branching", "None", "Reticulate"],
    patterns: [
      "None",
      "ThroatBlotch",
      "Flame",
      "Stripes",
      "Picotee",
      "Speckle",
    ],
    fusions: ["Tube", "Free", "Bell", "Funnel"],
    inflorescences: ["Spike", "Raceme", "Solitary", "Panicle"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [4, 5],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Simple", "Capitate"],
    stigmaShapes: ["Capitate", "Bifid", "Discoid"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Ovate", "Triangular", "Leaflike"],
    leafShapes: ["Lanceolate", "Ovate", "Elliptic", "Linear", "Cordate"],
    serrations: ["None", "Fine", "Dentate"],
    leafArrangements: ["Opposite", "Alternate", "Whorled"],
    stemStyles: ["Straight", "Arching", "Sinuous"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "pink",
      "yellow",
      "crimson",
      "white",
      "orange",
      "magenta",
      "peach",
      "coral",
      "violet",
      "burgundy",
      "cream",
    ],
    leafColor: "dark",
  },
  Gentianaceae: {
    key: "Gentianaceae",
    description:
      "gentian family: five petals fused into a deep funnel or bell, often ruffled and doubled like a soft rose, smooth blue green opposite leaves",
    examples: ["lisianthus", "gentian", "eustoma", "prairie gentian"],
    typicalGenus: "Eustoma",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 3],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Contorted", "Spiral", "Imbricate"],
    shapes: ["Obovate", "Spatulate", "Oblong", "Orbicular", "Deltoid"],
    innerShapes: ["Obovate", "Spatulate"],
    edges: ["Smooth", "Ruffled", "Undulate", "Plicate", "Fringed"],
    textures: ["Silk", "Smooth", "Velvet", "Glassy", "Papery"],
    veins: ["Branching", "Parallel", "None", "Reticulate"],
    patterns: ["None", "Picotee", "ThroatBlotch", "Stripes", "Spots", "Flame"],
    fusions: ["Funnel", "Free", "Bell", "Trumpet", "Tube"],
    inflorescences: ["Solitary", "Raceme", "Panicle", "Spray"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [5, 5],
    stamenProminence: ["visible", "hidden"],
    pistilStyles: ["Simple", "Split", "Capitate"],
    stigmaShapes: ["Bifid", "Capitate", "Lobed"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Aristate", "Tubular", "Triangular"],
    leafShapes: ["Ovate", "Lanceolate", "Elliptic", "Linear", "Obovate"],
    serrations: ["None"],
    leafArrangements: ["Opposite", "Decussate", "Basal"],
    stemStyles: ["Straight", "Arching"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "white",
      "lavender",
      "violet",
      "pink",
      "blue",
      "indigo",
      "cream",
      "blush",
      "magenta",
      "apricot",
    ],
    leafColor: "blue_green",
  },
  Campanulaceae: {
    key: "Campanulaceae",
    description:
      "bellflower family: nodding bells of five petals fused for most of their length with pointed lobes at the rim, mostly blue or violet, heart shaped basal leaves",
    examples: [
      "campanula",
      "bellflower",
      "Canterbury bells",
      "platycodon",
      "lobelia",
    ],
    typicalGenus: "Campanula",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Valvate", "Whorled", "Bilateral"],
    shapes: ["Deltoid", "Ovate", "Oblong", "Lanceolate", "Orbicular"],
    innerShapes: ["Deltoid", "Ovate"],
    edges: ["Smooth", "Lobed", "Undulate", "Rolled", "Ruffled"],
    textures: ["Silk", "Smooth", "Papery", "Glassy", "Velvet"],
    veins: ["Parallel", "Branching", "None"],
    patterns: ["None", "Speckle", "Spots", "Stripes", "ThroatBlotch"],
    fusions: ["Bell", "Urn", "Funnel", "Tube"],
    inflorescences: ["Solitary", "Raceme", "Spike", "Panicle"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [5, 5],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Split", "Simple", "Branched"],
    stigmaShapes: ["Trifid", "Bifid", "Lobed", "Capitate"],
    sepalCount: 5,
    sepalShapes: ["Lanceolate", "Triangular", "Aristate", "Leaflike"],
    leafShapes: [
      "Cordate",
      "Ovate",
      "Lanceolate",
      "Linear",
      "Reniform",
      "Orbicular",
    ],
    serrations: ["Dentate", "Crenate", "Fine", "None"],
    leafArrangements: ["Alternate", "Basal", "Rosette"],
    stemStyles: ["Straight", "Arching", "Trailing", "Sinuous"],
    thorns: false,
    bracts: false,
    special: "Bell",
    colors: [
      "blue",
      "violet",
      "lavender",
      "white",
      "sky",
      "indigo",
      "pink",
      "blush",
    ],
    leafColor: "dark",
  },
  Nymphaeaceae: {
    key: "Nymphaeaceae",
    description:
      "water lily family: floating solitary flowers of many pointed spoon shaped petals in spiralling rings around a golden boss of stamens, round floating leaves",
    examples: [
      "water lily",
      "lotus like water lily",
      "nymphaea",
      "spatterdock",
    ],
    typicalGenus: "Nymphaea",
    botanicalClass: "Basal",
    petalCounts: [8, 13, 21, 34],
    layerRange: [3, 5],
    symmetry: "Spiral",
    symmetryOrder: 0,
    arrangements: ["Spiral", "Whorled", "Imbricate"],
    shapes: ["Spatulate", "Lanceolate", "Oblong", "Obovate", "Acuminate"],
    innerShapes: ["Spatulate", "Lanceolate", "Filiform", "Cuneate"],
    edges: ["Smooth", "Undulate"],
    textures: ["Waxy", "Silk", "Smooth", "Glassy", "Pearlescent"],
    veins: ["Parallel", "None", "Branching"],
    patterns: ["None", "Band", "Flame", "Speckle"],
    fusions: ["Free"],
    inflorescences: ["Solitary"],
    disc: false,
    receptacleSize: [0.4, 0.7],
    stamenRange: [30, 150],
    stamenProminence: ["prominent", "brush", "visible"],
    pistilStyles: ["Compound", "Capitate", "Branched"],
    stigmaShapes: ["Discoid", "Stellate", "Lobed", "Capitate"],
    sepalCount: 4,
    sepalShapes: ["Petaloid", "Ovate", "Lanceolate", "Leaflike"],
    leafShapes: ["Peltate", "Orbicular", "Reniform", "Cordate"],
    serrations: ["None", "Dentate", "Crenate"],
    leafArrangements: ["Basal", "Rosette", "Alternate"],
    stemStyles: ["Straight", "Arching", "Sinuous", "Succulent"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "white",
      "pink",
      "yellow",
      "blue",
      "violet",
      "lavender",
      "magenta",
      "cream",
      "crimson",
      "peach",
    ],
    leafColor: "dark",
  },
  Passifloraceae: {
    key: "Passifloraceae",
    description:
      "passion flower family: five petals and five petal like sepals under a ring of banded thread like corona filaments and a raised central column, climbing vines with lobed leaves",
    examples: ["passion flower", "passiflora", "maypop", "granadilla"],
    typicalGenus: "Passiflora",
    botanicalClass: "Dicot",
    petalCounts: [5],
    layerRange: [2, 3],
    symmetry: "Radial",
    symmetryOrder: 5,
    arrangements: ["Radial", "Whorled", "Valvate"],
    shapes: ["Oblong", "Lanceolate", "Obovate", "Spatulate", "Ovate"],
    innerShapes: ["Filiform", "Laciniate", "Fimbriate", "Lanceolate"],
    edges: ["Smooth", "Undulate", "Fringed", "Crisped"],
    textures: ["Waxy", "Smooth", "Silk", "Glassy", "Papery"],
    veins: ["None", "Parallel", "Branching"],
    patterns: ["Band", "None", "Stripes", "Speckle", "Spots", "ThroatBlotch"],
    fusions: ["Free", "Tube"],
    inflorescences: ["Solitary"],
    disc: false,
    receptacleSize: [0.3, 0.6],
    stamenRange: [5, 5],
    stamenProminence: ["prominent", "visible"],
    pistilStyles: ["Branched", "Split", "Compound"],
    stigmaShapes: ["Capitate", "Trifid", "Clavate", "Discoid"],
    sepalCount: 5,
    sepalShapes: ["Petaloid", "Lanceolate", "Ovate", "Aristate"],
    leafShapes: ["Palmate", "Lyrate", "Ovate", "Cordate", "Hastate"],
    serrations: ["Lobed", "None", "Fine", "Dentate"],
    leafArrangements: ["Alternate"],
    stemStyles: ["Twining", "Trailing", "Sinuous", "Woody"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "violet",
      "white",
      "lavender",
      "indigo",
      "blue",
      "crimson",
      "magenta",
      "pink",
      "green",
      "lime",
      "cream",
    ],
    leafColor: "dark",
  },
  Proteaceae: {
    key: "Proteaceae",
    description:
      "protea family: a dense head of many narrow pointed florets wrapped in stiff showy pointed bracts, leathery leaves on thick woody stems",
    examples: [
      "protea",
      "king protea",
      "leucospermum",
      "leucadendron",
      "banksia",
      "grevillea",
    ],
    typicalGenus: "Protea",
    botanicalClass: "Dicot",
    petalCounts: [21, 34, 55],
    layerRange: [2, 4],
    symmetry: "Radial",
    symmetryOrder: 0,
    arrangements: ["Spiral", "Whorled", "Imbricate", "Radial"],
    shapes: ["Acuminate", "Lanceolate", "Filiform", "Ligulate", "Falcate"],
    innerShapes: ["Filiform", "Acuminate", "Lanceolate", "Fimbriate"],
    edges: ["Smooth", "Fringed", "Rolled", "Revolute"],
    textures: ["Leathery", "Velvet", "Hairy", "Fuzzy", "Silk", "Waxy"],
    veins: ["None", "Parallel"],
    patterns: ["None", "Band", "Picotee", "Flame"],
    fusions: ["Free", "Tube"],
    inflorescences: ["Solitary", "Spike", "Raceme", "Umbel"],
    disc: false,
    receptacleSize: [0.5, 0.9],
    stamenRange: [20, 80],
    stamenProminence: ["prominent", "brush", "hidden", "visible"],
    pistilStyles: ["Simple", "Branched", "Plumose"],
    stigmaShapes: ["Clavate", "Capitate", "Discoid"],
    sepalCount: 4,
    sepalShapes: ["Petaloid", "Lanceolate", "Aristate", "Leaflike"],
    leafShapes: [
      "Oblanceolate",
      "Lanceolate",
      "Elliptic",
      "Linear",
      "Obovate",
      "Acicular",
      "Bipinnate",
    ],
    serrations: ["None", "Spinose", "Lobed"],
    leafArrangements: ["Alternate", "Whorled"],
    stemStyles: ["Woody", "Straight"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "pink",
      "coral",
      "crimson",
      "cream",
      "white",
      "orange",
      "gold",
      "burgundy",
      "silver",
      "blush",
    ],
    leafColor: "dark",
  },
  Cactaceae: {
    key: "Cactaceae",
    description:
      "cactus family: large glossy flowers of many pointed tepals in spiralling rings around a mass of stamens, opening from a spiny succulent stem",
    examples: [
      "cactus flower",
      "echinopsis",
      "night blooming cereus",
      "prickly pear flower",
      "epiphyllum",
    ],
    typicalGenus: "Echinopsis",
    botanicalClass: "Dicot",
    petalCounts: [13, 21, 34],
    layerRange: [3, 5],
    symmetry: "Spiral",
    symmetryOrder: 0,
    arrangements: ["Spiral", "Imbricate", "Whorled"],
    shapes: ["Lanceolate", "Acuminate", "Oblong", "Spatulate", "Obovate"],
    innerShapes: ["Lanceolate", "Oblong", "Spatulate", "Acuminate"],
    edges: ["Smooth", "Dentate", "Undulate", "Erose", "Fringed"],
    textures: ["Waxy", "Glassy", "Silk", "Smooth", "Pearlescent", "Metallic"],
    veins: ["None", "Parallel"],
    patterns: ["None", "Band", "Flame", "Stripes", "ThroatBlotch"],
    fusions: ["Free", "Tube", "Funnel", "Trumpet"],
    inflorescences: ["Solitary"],
    disc: false,
    receptacleSize: [0.4, 0.7],
    stamenRange: [50, 300],
    stamenProminence: ["prominent", "brush", "visible"],
    pistilStyles: ["Branched", "Compound", "Split"],
    stigmaShapes: ["Stellate", "Lobed", "Trifid", "Plumose"],
    sepalCount: 8,
    sepalShapes: [
      "Petaloid",
      "Lanceolate",
      "Triangular",
      "Aristate",
      "Spatulate",
    ],
    leafShapes: ["Acicular", "Linear", "Spatulate", "Obovate"],
    serrations: ["Spinose", "None", "Ciliate"],
    leafArrangements: ["Whorled", "Rosette", "Alternate"],
    stemStyles: ["Succulent", "Straight", "Arching", "Woody"],
    thorns: true,
    bracts: false,
    special: "None",
    colors: [
      "magenta",
      "pink",
      "white",
      "yellow",
      "orange",
      "scarlet",
      "crimson",
      "coral",
      "gold",
      "cream",
      "violet",
    ],
    leafColor: "blue_green",
  },
  Orchidaceae: {
    key: "Orchidaceae",
    description:
      "orchid family: bilateral flowers of three sepals and three petals, the lowest petal a lip or labellum of a different shape and pattern, fused column in the center, arching sprays",
    examples: [
      "orchid",
      "phalaenopsis",
      "cymbidium",
      "dendrobium",
      "cattleya",
      "vanda",
    ],
    typicalGenus: "Phalaenopsis",
    botanicalClass: "Monocot",
    petalCounts: [3],
    layerRange: [2, 2],
    symmetry: "Bilateral",
    symmetryOrder: 0,
    arrangements: ["Zygomorphic", "Bilateral"],
    shapes: [
      "Ovate",
      "Orbicular",
      "Obovate",
      "Falcate",
      "Lanceolate",
      "Rhomboid",
    ],
    innerShapes: [
      "Panduriform",
      "Reniform",
      "Cordate",
      "Sagittate",
      "Laciniate",
      "Fimbriate",
      "Unguiculate",
    ],
    edges: ["Smooth", "Undulate", "Ruffled", "Fringed", "Crisped", "Lacerate"],
    textures: ["Waxy", "Velvet", "Silk", "Smooth", "Glassy", "Pearlescent"],
    veins: ["Branching", "Reticulate", "Parallel", "None", "Anastomosing"],
    patterns: [
      "None",
      "Spots",
      "Speckle",
      "Stripes",
      "ThroatBlotch",
      "Flame",
      "Picotee",
      "Band",
    ],
    fusions: ["Free", "Tube"],
    inflorescences: ["Solitary", "Raceme", "Spike", "Panicle", "Spray"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [1, 2],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Capitate", "Simple", "Compound"],
    stigmaShapes: ["Discoid", "Capitate", "Lobed", "Clavate"],
    sepalCount: 3,
    sepalShapes: ["Petaloid", "Lanceolate", "Ovate", "Spatulate"],
    leafShapes: [
      "Elliptic",
      "Oblanceolate",
      "Lanceolate",
      "Linear",
      "Ovate",
      "Obovate",
    ],
    serrations: ["None"],
    leafArrangements: ["Distichous", "Basal", "Alternate", "Rosette"],
    stemStyles: ["Arching", "Straight", "Sinuous", "Zigzag"],
    thorns: false,
    bracts: false,
    special: "Labellum",
    colors: [
      "white",
      "magenta",
      "pink",
      "violet",
      "lavender",
      "yellow",
      "burgundy",
      "lime",
      "green",
      "cream",
      "peach",
      "orange",
      "brown",
    ],
    leafColor: "dark",
  },
  Liliaceae: {
    key: "Liliaceae",
    description:
      "lily family: six pointed tepals in two whorls of three, often recurved or flared into a trumpet, six long stamens with heavy anthers, strap leaves",
    examples: ["lily", "tulip", "fritillary", "Asiatic lily", "Oriental lily"],
    typicalGenus: "Lilium",
    botanicalClass: "Monocot",
    petalCounts: [6],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 3,
    arrangements: ["Radial", "Whorled", "Imbricate", "Valvate"],
    shapes: [
      "Lanceolate",
      "Acuminate",
      "Oblong",
      "Spatulate",
      "Ovate",
      "Obovate",
    ],
    innerShapes: ["Lanceolate", "Obovate", "Spatulate"],
    edges: ["Smooth", "Undulate", "Rolled", "Revolute", "Ruffled"],
    textures: ["Waxy", "Silk", "Smooth", "Velvet", "Glassy"],
    veins: ["Parallel", "None", "Branching"],
    patterns: [
      "None",
      "Spots",
      "Speckle",
      "Band",
      "Flame",
      "ThroatBlotch",
      "Picotee",
    ],
    fusions: ["Free", "Trumpet", "Funnel", "Bell"],
    inflorescences: ["Solitary", "Raceme", "Umbel", "Spray", "Panicle"],
    disc: false,
    receptacleSize: [0.2, 0.4],
    stamenRange: [6, 6],
    stamenProminence: ["prominent", "visible", "hidden"],
    pistilStyles: ["Simple", "Split", "Capitate"],
    stigmaShapes: ["Trifid", "Lobed", "Capitate", "Clavate"],
    sepalCount: 3,
    sepalShapes: ["Petaloid", "Lanceolate", "Ovate", "Leaflike"],
    leafShapes: ["Lanceolate", "Linear", "Elliptic", "Ovate", "Oblanceolate"],
    serrations: ["None"],
    leafArrangements: ["Alternate", "Whorled", "Basal", "Distichous"],
    stemStyles: ["Straight", "Arching", "Sinuous"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "white",
      "pink",
      "orange",
      "yellow",
      "crimson",
      "scarlet",
      "peach",
      "gold",
      "cream",
      "magenta",
      "burgundy",
      "violet",
    ],
    leafColor: "dark",
  },
  Iridaceae: {
    key: "Iridaceae",
    description:
      "iris family: three drooping outer falls and three upright inner standards, often bearded or veined with a contrasting signal, sword like leaves in a flat fan",
    examples: ["iris", "freesia", "gladiolus", "crocus", "ixia"],
    typicalGenus: "Iris",
    botanicalClass: "Monocot",
    petalCounts: [3],
    layerRange: [2, 2],
    symmetry: "Radial",
    symmetryOrder: 3,
    arrangements: ["Whorled", "Radial", "Bilateral", "Valvate"],
    shapes: ["Obovate", "Spatulate", "Oblong", "Falcate", "Lanceolate"],
    innerShapes: [
      "Obovate",
      "Spatulate",
      "Orbicular",
      "Unguiculate",
      "Cuneate",
    ],
    edges: ["Undulate", "Ruffled", "Smooth", "Crisped", "Fringed"],
    textures: ["Silk", "Velvet", "Smooth", "Papery", "Waxy"],
    veins: ["Branching", "Reticulate", "Parallel", "Dichotomous", "None"],
    patterns: [
      "None",
      "ThroatBlotch",
      "Stripes",
      "Flame",
      "Speckle",
      "Picotee",
      "Band",
      "Spots",
    ],
    fusions: ["Free", "Tube", "Funnel", "Trumpet"],
    inflorescences: ["Solitary", "Spike", "Raceme", "Spray"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [3, 3],
    stamenProminence: ["hidden", "visible"],
    pistilStyles: ["Branched", "Split", "Compound"],
    stigmaShapes: ["Trifid", "Lobed", "Fimbriate", "Plumose"],
    sepalCount: 3,
    sepalShapes: ["Petaloid", "Spatulate", "Lanceolate"],
    leafShapes: ["Linear", "Lanceolate", "Falcate"],
    serrations: ["None"],
    leafArrangements: ["Distichous", "Basal", "Alternate"],
    stemStyles: ["Straight", "Arching", "Zigzag"],
    thorns: false,
    bracts: true,
    special: "None",
    colors: [
      "violet",
      "indigo",
      "blue",
      "yellow",
      "white",
      "lavender",
      "gold",
      "burgundy",
      "magenta",
      "orange",
      "cream",
      "peach",
      "sky",
      "black",
    ],
    leafColor: "blue_green",
  },
  Amaryllidaceae: {
    key: "Amaryllidaceae",
    description:
      "amaryllis family: six tepals around a central corona cup or trumpet, one or more flowers from a papery spathe at the top of a hollow leafless stalk, strap leaves",
    examples: [
      "daffodil",
      "narcissus",
      "amaryllis",
      "agapanthus",
      "allium",
      "snowdrop",
    ],
    typicalGenus: "Narcissus",
    botanicalClass: "Monocot",
    petalCounts: [6],
    layerRange: [2, 2],
    symmetry: "Radial",
    symmetryOrder: 3,
    arrangements: ["Radial", "Whorled", "Valvate", "Imbricate"],
    shapes: [
      "Ovate",
      "Lanceolate",
      "Obovate",
      "Oblong",
      "Spatulate",
      "Acuminate",
    ],
    innerShapes: ["Tubular", "Ovate", "Deltoid", "Orbicular", "Lanceolate"],
    edges: ["Smooth", "Ruffled", "Undulate", "Crisped", "Fringed", "Dentate"],
    textures: ["Silk", "Smooth", "Papery", "Waxy", "Velvet"],
    veins: ["Parallel", "None", "Branching"],
    patterns: ["None", "Band", "Picotee", "Stripes", "Flame", "ThroatBlotch"],
    fusions: ["Free", "Trumpet", "Funnel", "Tube", "Bell"],
    inflorescences: ["Solitary", "Umbel", "Spray"],
    disc: false,
    receptacleSize: [0.2, 0.4],
    stamenRange: [6, 6],
    stamenProminence: ["visible", "hidden", "prominent"],
    pistilStyles: ["Simple", "Split", "Capitate"],
    stigmaShapes: ["Trifid", "Capitate", "Lobed", "Clavate"],
    sepalCount: 3,
    sepalShapes: ["Petaloid", "Lanceolate", "Ovate", "Leaflike"],
    leafShapes: ["Linear", "Lanceolate", "Oblanceolate", "Falcate"],
    serrations: ["None"],
    leafArrangements: ["Basal", "Distichous", "Alternate"],
    stemStyles: ["Straight", "Arching"],
    thorns: false,
    bracts: true,
    special: "Corona",
    colors: [
      "yellow",
      "white",
      "gold",
      "orange",
      "cream",
      "peach",
      "scarlet",
      "crimson",
      "pink",
      "coral",
      "blush",
      "lime",
      "violet",
    ],
    leafColor: "blue_green",
  },
  Asparagaceae: {
    key: "Asparagaceae",
    description:
      "hyacinth family: many small six lobed bells or stars crowded up a raceme from a bulb, fleshy strap leaves, heavy fragrance",
    examples: [
      "hyacinth",
      "bluebell",
      "grape hyacinth",
      "agave",
      "hosta",
      "yucca",
    ],
    typicalGenus: "Hyacinthus",
    botanicalClass: "Monocot",
    petalCounts: [6],
    layerRange: [1, 2],
    symmetry: "Radial",
    symmetryOrder: 3,
    arrangements: ["Radial", "Whorled", "Valvate"],
    shapes: [
      "Oblong",
      "Lanceolate",
      "Spatulate",
      "Ovate",
      "Ligulate",
      "Deltoid",
    ],
    innerShapes: ["Oblong", "Lanceolate"],
    edges: ["Smooth", "Rolled", "Revolute", "Undulate", "Ruffled"],
    textures: ["Waxy", "Silk", "Smooth", "Glassy", "Velvet"],
    veins: ["Parallel", "None", "Branching"],
    patterns: ["None", "Stripes", "Band", "Picotee", "Speckle"],
    fusions: ["Bell", "Free", "Tube", "Urn", "Funnel"],
    inflorescences: ["Solitary", "Raceme", "Spike", "Panicle", "Umbel"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [6, 6],
    stamenProminence: ["hidden", "visible", "prominent"],
    pistilStyles: ["Simple", "Split", "Capitate"],
    stigmaShapes: ["Capitate", "Trifid", "Lobed", "Discoid"],
    sepalCount: 3,
    sepalShapes: ["Petaloid", "Lanceolate", "Ovate"],
    leafShapes: [
      "Linear",
      "Lanceolate",
      "Oblanceolate",
      "Elliptic",
      "Falcate",
      "Sagittate",
    ],
    serrations: ["None", "Spinose"],
    leafArrangements: [
      "Basal",
      "Rosette",
      "Whorled",
      "Alternate",
      "Distichous",
    ],
    stemStyles: ["Straight", "Arching", "Succulent", "Twining"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "blue",
      "violet",
      "lavender",
      "white",
      "pink",
      "indigo",
      "cream",
      "magenta",
      "yellow",
      "blush",
      "sky",
    ],
    leafColor: "dark",
  },
  Alstroemeriaceae: {
    key: "Alstroemeriaceae",
    description:
      "alstroemeria family: six tepals in two whorls, the inner three narrower and streaked with dark speckles and stripes, several flowers in a loose umbel, twisted leaves",
    examples: ["alstroemeria", "Peruvian lily", "lily of the Incas", "bomarea"],
    typicalGenus: "Alstroemeria",
    botanicalClass: "Monocot",
    petalCounts: [6],
    layerRange: [2, 2],
    symmetry: "Radial",
    symmetryOrder: 3,
    arrangements: ["Whorled", "Radial", "Bilateral", "Zygomorphic"],
    shapes: ["Obovate", "Spatulate", "Oblong", "Lanceolate", "Unguiculate"],
    innerShapes: ["Unguiculate", "Lanceolate", "Spatulate", "Oblong"],
    edges: ["Smooth", "Undulate", "Dentate", "Erose"],
    textures: ["Silk", "Smooth", "Velvet", "Waxy"],
    veins: ["Branching", "Parallel", "None"],
    patterns: [
      "Speckle",
      "Stripes",
      "None",
      "Flame",
      "Spots",
      "ThroatBlotch",
      "Band",
    ],
    fusions: ["Free", "Funnel", "Trumpet"],
    inflorescences: ["Solitary", "Umbel", "Spray", "Panicle"],
    disc: false,
    receptacleSize: [0.1, 0.3],
    stamenRange: [6, 6],
    stamenProminence: ["prominent", "visible", "hidden"],
    pistilStyles: ["Split", "Simple", "Branched"],
    stigmaShapes: ["Trifid", "Lobed", "Capitate"],
    sepalCount: 3,
    sepalShapes: ["Petaloid", "Spatulate", "Lanceolate", "Ovate"],
    leafShapes: ["Lanceolate", "Elliptic", "Oblanceolate", "Linear", "Ovate"],
    serrations: ["None"],
    leafArrangements: ["Alternate", "Whorled", "Distichous"],
    stemStyles: ["Straight", "Arching", "Sinuous", "Zigzag"],
    thorns: false,
    bracts: false,
    special: "None",
    colors: [
      "orange",
      "pink",
      "yellow",
      "white",
      "coral",
      "crimson",
      "peach",
      "lavender",
      "magenta",
      "cream",
      "burgundy",
      "apricot",
      "gold",
    ],
    leafColor: "dark",
  },
};
