// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SessionStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
  get status() {
    return SessionStatus;
  },
  prompt: __t.string(),
  canvasX: __t.f64().name("canvas_x"),
  canvasY: __t.f64().name("canvas_y"),
  arrangementLevel: __t.u32().name("arrangement_level"),
  flowerCount: __t.u32().name("flower_count"),
  generation: __t.u32(),
});
