// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  environmentId: __t.u64().name("environment_id"),
  sessionId: __t.u64().name("session_id"),
  owner: __t.identity(),
  score: __t.f64(),
  rank: __t.u32(),
  flowerName: __t.string().name("flower_name"),
  updatedAt: __t.timestamp().name("updated_at"),
});
