// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SkinRarity,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  description: __t.string(),
  get rarity() {
    return SkinRarity;
  },
  unlockXp: __t.u64().name("unlock_xp"),
  cssClass: __t.string().name("css_class"),
});
