// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  sender: __t.identity(),
  text: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const FlowerOrder = __t.object("FlowerOrder", {
  id: __t.u64(),
  sessionId: __t.u64(),
  orderer: __t.identity(),
  orderedAt: __t.timestamp(),
  get source() {
    return OrderSource;
  },
  note: __t.option(__t.string()),
});
export type FlowerOrder = __Infer<typeof FlowerOrder>;

export const FlowerPartOverride = __t.object("FlowerPartOverride", {
  id: __t.u64(),
  sessionId: __t.u64(),
  partPath: __t.string(),
  overrideJson: __t.string(),
  forkedFrom: __t.string(),
  createdAt: __t.timestamp(),
});
export type FlowerPartOverride = __Infer<typeof FlowerPartOverride>;

export const FlowerSession = __t.object("FlowerSession", {
  id: __t.u64(),
  owner: __t.identity(),
  createdAt: __t.timestamp(),
  get status() {
    return SessionStatus;
  },
  prompt: __t.string(),
  canvasX: __t.f64(),
  canvasY: __t.f64(),
  arrangementLevel: __t.u32(),
  flowerCount: __t.u32(),
  generation: __t.u32(),
});
export type FlowerSession = __Infer<typeof FlowerSession>;

export const FlowerSpec = __t.object("FlowerSpec", {
  sessionId: __t.u64(),
  spec: __t.string(),
  version: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type FlowerSpec = __Infer<typeof FlowerSpec>;

// The tagged union or sum type for the algebraic type `OrderSource`.
export const OrderSource = __t.enum("OrderSource", {
  Human: __t.unit(),
  Agent: __t.unit(),
});
export type OrderSource = __Infer<typeof OrderSource>;

// The tagged union or sum type for the algebraic type `SessionStatus`.
export const SessionStatus = __t.enum("SessionStatus", {
  Designing: __t.unit(),
  Ordered: __t.unit(),
  Complete: __t.unit(),
});
export type SessionStatus = __Infer<typeof SessionStatus>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  currentSessionId: __t.option(__t.u64()),
  totalOrders: __t.u32(),
  joinedAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

