// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  currentSessionId: __t.option(__t.u64()).name("current_session_id"),
  totalOrders: __t.u32().name("total_orders"),
  xp: __t.u64(),
  level: __t.u32(),
  joinedAt: __t.timestamp().name("joined_at"),
});
